# This Docker Compose file sets up a local Prometheus and Grafana development environment using Docker containers.
# The 'prometheus_srv' and 'grafana_srv' services use the latest official Prometheus and Graphana Docker images.
# The Prometheus and Graphana containers' ports 9090 and 3000 are exposed to the host machine ports 9090 and 3000 respectively, so the respective interfaces can be remotely accessible via a browser.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
# Required configuration and data sources details are incliuded in /prometheus and /grafana folders respectively.
# To connect to Grafana, you need to use the followng credentials (usenname:admin & password:grafana).
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:

  # Prometheus Service Section
  prometheus_srv:
    image: prom/prometheus
    container_name: monitor_prometheus
    restart: always
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus
      - monitor_prom_data_vol:/prometheus
    networks:
      - monitor_prom_net

  # Grafana Service Section
  grafana_srv:
    image: grafana/grafana
    container_name: monitor_grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - monitor_graf_data_vol://var/lib/grafana
    networks:
      - monitor_prom_net

# Shared Resources Section
volumes:
  monitor_prom_data_vol:
  monitor_graf_data_vol:  
networks:
  monitor_prom_net: