# This Docker Compose file sets up a local phpMyAdmin instance using Docker containers.
# The 'phpmyadmin_srv' service uses the latest official phpMyAdmin Docker image.
# The phpMyAdmin container's port 80 is exposed to the host machine port 8081, so as databases can be accessed remotely from respective web interface.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
# You will be required to enter the database servers' IP/FQDN and respective credentials to connect.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:

  # phpmyadmin Service Section
  phpmyadmin_srv:
    image: phpmyadmin:latest
    container_name: phpmyadmin_srv
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - /sessions

# Shared Resources Section