# This Docker Compose file sets up a local PostgreSQL instance using Docker containers.
# The 'postgresql_srv' service uses the latest official PostgreSQL image.
# The PostgreSQL container's port 5432 is exposed to the host machine port 5432, so as databases can be accessed remotely.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
# You will be required to enter the database credentials (username:you@email.com password:admin) to connect.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:
  
  # PostgreSQL Service Section
  postgresqldb_srv:
    image: postgres:latest
    container_name: db_postgresql_srv
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passsword
      - POSTGRES_DB=postgres
    volumes:
      - db_postgres_data_vol:/var/lib/postgresql/data
      
# Shared Resources Section
volumes:
  db_postgres_data_vol: