# This Docker Compose file sets up local PostgreSQL and pgAdmin instances using Docker containers.
# The 'postgresql_srv' and 'pgadmin_srv' services use the official Docker images.
# We expose the PostgreSQL container's port 5432 to the host machine port 5432, so we can access the databases remotely.
# We also expose the container's port 80 to the host machine port 8888, so as to be able to manage PostgreSQL databases from respective web interface.
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.

version: "3"

# Services Definitions
services:
  
  # PostgreSQL Service Section
  postgresqldb_srv:
    image: postgres:latest
    container_name: db_postgresql_srv
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_postgres_data_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=postgres
    networks:
      - db_postgres_net

  # pgAdmin Service Section
  pgadmin_srv:
    image: dpage/pgadmin4:latest
    container_name: db_pgadmin_srv
    restart: always
    depends_on:
      - postgresqldb_srv
    ports:
      - 8888:80
    volumes:
      - db_pgadmin_data_vol:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - db_postgres_net
      
# Shared Resources Section
volumes:
  db_postgres_data_vol:
  db_pgadmin_data_vol:
networks:
  db_postgres_net: