# This Docker Compose file sets up a local Apache instance using Docker containers.
# The 'apache_srv' service uses the official Apache Docker image.
# The Apache container's port 89 is exposed to the host machine port 8080, so as web sites can be accessed remotely.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:

  # Apache Service Section
  apache_srv:
    image: httpd:latest
    container_name: apache_srv
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./website:/usr/local/apache2/htdocs

# Shared Resources Section