# This Docker Compose file sets up a local Nginx instance using Docker containers.
# The 'nginx_srv' service uses the latest official Nginx Docker image.
# The Apache container's port 80 is exposed to the host machine port 8080, so as web sites can be accessed remotely.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:

  # Nginx Service Section
  nginx_srv:
    image: nginx:latest
    container_name: nginx_srv
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./http:/usr/share/nginx/html

# Shared Resources Section