# This Docker Compose file sets up a local MySQL instance using Docker containers.
# The 'mysql_srv' service uses the latest official MySQL image.
# The MySQL container's port 3306 is exposed to the host machine port 3306, so as databases can be accessed remotely.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
# You will be required to enter the database credentials (username:root password:password) to connect.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:

  # MySQL Service Section
  mysql_srv:
    image: mysql:latest
    container_name: db_mysql_srv
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_mysql_data_vol:/var/lib/mysql

# Shared Resources Section
volumes:
  db_mysql_data_vol: