# This Docker Compose file sets up local MySQL and phpMyAdmin instances using Docker containers.
# The 'mysql_srv' and 'phpmyadmin_srv' services use the official Docker images.
# We expose the MySQL container's port 3306 to the host machine port 3306, so we can access the databases remotely.
# We also expose the container's port 80 to the host machine port 8888, so as to be able to manage MySQL databases from respective web interface.
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.

version: "3"

# Services Definitions
services:

  # MySQL Service Section
  mysql_srv:
    image: mysql:latest
    container_name: db_mysql_srv
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_mysql_data_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - db_mysql_net

  # phpmyadmin Service Section
  phpmyadmin_srv:
    image: phpmyadmin:latest
    container_name: db_phpmyadmin_srv
    restart: always
    depends_on:
      - mysql_srv
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql_srv
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - db_mysql_net

# Shared Resources Section
volumes:
  db_mysql_data_vol:
networks:
  db_mysql_net: