# This Docker Compose file sets up local MySQL and phpMyAdmin instances using Docker containers.
# The 'mysql_srv' and 'phpmyadmin_srv' services use the latest official MySQL and phpMyAdmin Docker images.
# The MySQL container's port 3306 is exposed to the host machine port 3306, so as databases can be accessed remotely.
# The phpMyAdmin container's port 80 is also exposed to the host machine port 8888, so as MySQL can be managed remotely from respective web interface.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
# You will be required to enter the database credentials (username:root password:password) to connect.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:

  # MySQL Service Section
  mysql_srv:
    image: mysql:latest
    container_name: db_mysql_srv
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_mysql_data_vol:/var/lib/mysql

  # phpmyadmin Service Section
  phpmyadmin_srv:
    image: phpmyadmin:latest
    container_name: db_phpmyadmin_srv
    restart: always
    depends_on:
      - mysql_srv
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql_srv
      MYSQL_ROOT_PASSWORD: password 

# Shared Resources Section
volumes:
  db_mysql_data_vol: