# This Docker Compose file sets up local MariaDB and phpMyAdmin instances using Docker containers.
# The 'mariadb_srv' and 'phpmyadmin_srv' services use the latest official MariaDB and phpMyAdmin Docker images.
# The MariaDB container's port 3306 is exposed to the host machine port 3306, so as databases can be accessed remotely.
# The phpMyAdmin container's port 80 is also exposed to the host machine port 8888, so as MariaDB databases can be managed remotely from respective web interface.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
# You will be required to enter the database credentials (username:user password:user) to connect.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:

  # MariaDB Service Section
  mariadb_srv:
    image: mariadb:latest
    container_name: db_mariadb_srv
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    volumes:
      - db_mariadb_data_vol:/var/lib/mysql
    networks:
      - db_mariadb_net

  # phpmyadmin Service Section
  phpmyadmin_srv:
    image: phpmyadmin:latest
    container_name: db_phpmyadmin_srv
    restart: always
    depends_on:
      - mariadb_srv
    ports:
      - 8888:80
    environment:
      PMA_HOST: mariadb_srv
      MARIADB_ROOT_PASSWORD: password 
    networks:
      - db_mariadb_net

# Shared Resources Section
volumes:
  db_mariadb_data_vol:
networks:
  db_mariadb_net: