# This Docker Compose file sets up a local MariaDB instance using Docker containers.
# The 'mariadb_srv' service uses the latest official MariaDB Docker image.
# The MariaDB container's port 3306 is exposed to the host machine port 3306, so as databases can be accessed remotely.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
# You will be required to enter the database credentials (username:user password:user) to connect.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:

  # MariaDB Service Section
  mariadb_srv:
    image: mariadb:latest
    container_name: db_mariadb_srv
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    volumes:
      - db_mariadb_data_vol:/var/lib/mysql

# Shared Resources Section
volumes:
  db_mariadb_data_vol: