# This Docker Compose file sets up a local MongoDB instance using Docker containers.
# The 'mongodb_srv' service uses the latest official MongoDB Docker image.
# The MongoDB container's port 27017 is exposed to the host machine port 27017, so as databases can be accessed remotely.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
# You will be required to enter the database credentials (username:root password:password) to connect.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3"

# Services Definitions
services:

  # MongoDB Service Section
  mongodb_srv:
    image: mongo:latest
    container_name: db_mongodb_srv
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db_mongo_datadb_vol:/data/db
      - db_mongo_dataconf_vol:/data/configdb
      - db_mongo_archive_vol:/Databases/dev.archive
      - db_mongo_production_vol:/Databases/production
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

# Shared Resources Section
volumes:
  db_mongo_datadb_vol:
  db_mongo_dataconf_vol:
  db_mongo_archive_vol:
  db_mongo_production_vol: