# This Docker Compose file sets up a local Joomla development environment using Docker containers.
# The 'joomla_srv' and 'mysqldb_srv' services use the latest official Joomla and MySQL Docker images.
# The MySQL container's port 3306 is exposed to the host machine port 3306, so as databases can be accessed remotely.
# The Joomla container's port 80 is also exposed to the host machine port 8000, so as the Joomla webiste can be managed remotely from respective web interface.
# The Joomla files are also mapped to a local directory, and variables are used to configure the database settings.
#
# To start the environment, run 'docker compose up -d' in this directory, and to stop it, run 'docker compose down'.
# You will be asked to setup the the Wordpres site details during initialisation step of the setup.
#
# The following sample is intended for use in local development environments such as project setups, etc. 
# This sample must not be deployed in production environments.

version: "3" 

# Services Definitions
services:
 
  # Joomla Service Section
  joomla_srv:
    image: joomla:latest
    container_name: joomla_cms
    restart: always
    depends_on:
      - mysqldb_srv
    ports:
      - 8080:80
    volumes:
      - ./site:/var/www/html
    environment:
      JOOMLA_DB_HOST: mysqldb_srv
      JOOMLA_DB_PASSWORD: password
    networks:
      - joomla_net

  # mySQL Service Section
  mysqldb_srv:
    image: mysql:latest
    container_name: joomla_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: joomla
#      MYSQL_USER: juser
#      MYSQL_PASSWORD: joomlapass
    volumes:
      - joomla_data:/var/lib/mysql
    networks:
      - joomla_net

# Shared Resources Section
volumes:
  joomla_data:
networks:
  joomla_net: